SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE, 'YY-MM'), TO_CHAR(HIREDATE,
'YYYY/MM/DD DAY') FROM employee;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD, HH24:MI:SS') FROM DUAL;

SELECT ENAME, TO_CHAR(SALARY, 'L999,999') FROM employee;

select ename, hirEdate, to_char(hiredate, 'YY-MM'), to_char(hiredate, 'YYYY//MM/DD DAY')
FROM EMPLOYEE;

SLECET TO_CHAR(SYSDATE, 'YYYY/MM/DD, HH24:MI:SS') FROM DAUL;

SELECT ENAME, TO_CHAR(SALARY, 'L999,999') FROM EMPLOYEE;

SELECT TO_NUMBER('100,000', '999,999')-TO_NUMBER('50,000','999,999')FROM DUAL; --특정 데이터를 숫자형으로 변환
--정해진 테이블이 없는 값을 쓸 경우 DUAL을 이용해 가상의 테이블을 만들어준다